env:
  browser: true
  es6: true
  mocha: true
extends: 'eslint:recommended'
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
  expect: true
  global: true
  require: true
  process: true

parserOptions:
  ecmaVersion: 2018
  sourceType: module
rules: {}
